### ISSUE TITLE
Webpack build system upgrade tracker

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#1356]
Remaining action items:
- [x] environment config https://github.com/angular/angular-cli/pull/1364
- [x] path mapping https://github.com/angular/angular-cli/pull/1359
- [x] sass/less/stylus (tests) https://github.com/angular/angular-cli/pull/1363
- [x] ng test errors https://github.com/angular/angular-cli/pull/1359
- [x] remove `require` from test shim https://github.com/angular/angular-cli/pull/1359
- [x] remove SystemJS dependency https://github.com/angular/angular-cli/pull/1376
- [x] ~~figure out lazy loading~~
- [x] remove vendor.ts https://github.com/angular/angular-cli/pull/1383
- [x] remove material2 specific options https://github.com/angular/angular-cli/pull/1385
- [x] `--source-dir` support https://github.com/angular/angular-cli/pull/1378
- [x] clean up broccoli remnants https://github.com/angular/angular-cli/pull/1386
- [x] remove windows elevation check https://github.com/angular/angular-cli/pull/1384
- [x] fix prod builds https://github.com/angular/angular-cli/pull/1395
- [x] add `ng e2e` test using prod builds https://github.com/angular/angular-cli/pull/1394
- [x] overall cleanup https://github.com/angular/angular-cli/pull/1388
- [x] disable HMR https://github.com/angular/angular-cli/pull/1402
- [x] review documentation https://github.com/angular/angular-cli/pull/1407
- [x] support arbitrary environments in runtime config https://github.com/angular/angular-cli/pull/1404
- [x] squiggly lines on editor with decorator errors https://github.com/angular/angular-cli/pull/1420
- [x] fix `libs` option in `tsconfig.json` https://github.com/angular/angular-cli/pull/1425
- [x] remove `module.id` https://github.com/angular/angular-cli/pull/1426
- [x] use karma config and remove reporters https://github.com/angular/angular-cli/pull/1437
- [x] re-add outDir to an ignored folder https://github.com/angular/angular-cli/pull/1428
- [x] add host options to `ng serve` https://github.com/angular/angular-cli/pull/1442
- [x] add @types support https://github.com/angular/angular-cli/pull/1449
- [x] sourcemaps in unit tests don't work https://github.com/angular/angular-cli/pull/1447

Things to investigate:
- [ ] using fonts https://github.com/angular/angular-cli/issues/1356#issuecomment-235020027
- [ ] problems building ngrx/angularfire2 https://github.com/angular/angular-cli/issues/1356#issuecomment-234930265

**Comment by RobCannon** [comment]
I would love to help with this.  Is there more detail on these action items?

**Comment by cortopy** [comment]
Me too. Right now, I have to mix&match angular-cli with my webpack config. I would like to help in order to get this feature released

**Comment by filipesilva** [comment]
Hi @RobCannon and @cortopy, we already have some people assigned to these and are working on getting them done as fast as possible. 

I don't think more help would be helpful right now though... too many cooks in the kitchen so to say, but thank you for offering!

**Comment by yusijs** [comment]
Does this mean you're leaving SystemJS behind? And will you provide an upgrade route in that case through ng upgrade or similar? I've built a fairly large app with the cli now, and I'd rather not scrap it.. :3

**Comment by filipesilva** [comment]
@yusijs there will be an upgrade route, yes. We will document it.

**Comment by RobCannon** [comment]
Can you tell me to load a .scss file?  I see there is sass support built in and I am able to get .scss files to process for individual components, but I can't figure out how to load a master style for the whole web app.

**Comment by TheLarkInn** [comment]
3 off the list thanks to #1359

**Comment by filipesilva** [comment]
@RobCannon there is no such functionality present in `angular-cli`. You'll have to use standard scss functionality for that.

**Comment by hansl** [comment]
@filipesilva, @TheLarkInn: We're punting lazy loading until the webpack branch makes it to master. It's a difficult problem with many moving pieces and we will need a proper prototyping and design phase to solve it.

**Comment by tapas4java** [comment]
Great work @filipesilva and @TheLarkInn. I can confirm SCSS is working out of the box with `--style scss` flag. `ng test` and `ng build --prod` broken though

**Comment by filipesilva** [comment]
@tapas4java broken? How? Tell me more. It's working in our tests. Did you run `ng init` to update your files?

**Comment by tapas4java** [comment]
@filipesilva I have created new project and ran `ng test`

```
Tapass-MacBook-Pro:digiadmin tapas-pc$ ng test
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.

ERROR in Entry module not found: Error: Can't resolve '/Users/tapas-pc/Documents/Work/digiadmin/undefined/test.ts' in '/Users/tapas-pc/Documents/Work/OpenSourceWork/Angular/angular-cli/addon/ng2/models'

ERROR in Entry module not found: Error: Can't resolve 'sourcemap-istanbul-instrumenter-loader' in '/Users/tapas-pc/Documents/Work/OpenSourceWork/Angular/angular-cli/addon/ng2/models'
```

**Comment by filipesilva** [comment]
@tapas4java looks like missing dependencies. Did you `npm install` on the webpack branch after checking it out? I know that these dependencies work, because our CI installs a project from scratch.

**Comment by tapas4java** [comment]
Thanks @filipesilva ....After `npm install` tests are working fine. But still getting below message even though it is not blocking anything. Not sure what is that `undefined` in the path.

`ERROR in Entry module not found: Error: Can't resolve '/Users/tapas-pc/Documents/Work/digiadmin/undefined/test.ts' in '/Users/tapas-pc/Documents/Work/OpenSourceWork/Angular/angular-cli/addon/ng2/models'`

**Comment by TheLarkInn** [comment]
Is this the only command that fails like this?

**Comment by filipesilva** [comment]
@tapas4java can you show me your `angular-cli.json`?

**Comment by filipesilva** [comment]
@tapas4java fixed in https://github.com/angular/angular-cli/pull/1387

**Comment by tapas4java** [comment]
Thanks @filipesilva, `ng test` is fine now. However `ng serve -prod` throwing bunch of warnings in terminal and not able to load on browser.

```
WARNING in CachePlugin - Cache cannot be used because of: DedupePlugin

WARNING in main.b9fc88ca36935dab7714.bundle.js from UglifyJs
Side effects in initialization of unused variable TypeModifier [main.b9fc88ca36935dab7714.bundle.js:640,4]
Side effects in initialization of unused variable BuiltinMethod [main.b9fc88ca36935dab7714.bundle.js:896,4]
Side effects in initialization of unused variable StmtModifier [main.b9fc88ca36935dab7714.bundle.js:1130,4]
Condition left of && always true [main.b9fc88ca36935dab7714.bundle.js:3766,17]
Side effects in initialization of unused variable ProviderAstType [main.b9fc88ca36935dab7714.bundle.js:5094,4]
Side effects in initialization of unused variable PropertyBindingType [main.b9fc88ca36935dab7714.bundle.js:5135,4]
Side effects in initialization of unused variable freeExports [main.b9fc88ca36935dab7714.bundle.js:8040,4]
Side effects in initialization of unused variable freeModule [main.b9fc88ca36935dab7714.bundle.js:8041,4]
Non-strict equality against boolean: != true [main.b9fc88ca36935dab7714.bundle.js:9594,15]
Side effects in initialization of unused variable ViewType [main.b9fc88ca36935dab7714.bundle.js:11402,4]
Side effects in initialization of unused variable HTMLCollection [main.b9fc88ca36935dab7714.bundle.js:13888,4]
Side effects in initialization of unused variable shim [main.b9fc88ca36935dab7714.bundle.js:17207,12]
Dropping unused variable SAFE_SRCSET_PATTERN [main.b9fc88ca36935dab7714.bundle.js:20936,4]
Side effects in initialization of unused variable matchs [main.b9fc88ca36935dab7714.bundle.js:22537,12]
Dropping unused variable __unused [main.b9fc88ca36935dab7714.bundle.js:22778,4]
Side effects in initialization of unused variable depTemplates [main.b9fc88ca36935dab7714.bundle.js:24737,12]
Dropping unused variable EVENT [main.b9fc88ca36935dab7714.bundle.js:24880,4]
Dropping unused variable __unused [main.b9fc88ca36935dab7714.bundle.js:28456,4]
Side effects in initialization of unused variable SecurityContext [main.b9fc88ca36935dab7714.bundle.js:32483,4]
Condition always true [main.b9fc88ca36935dab7714.bundle.js:34846,4]
Dropping unreachable code [main.b9fc88ca36935dab7714.bundle.js:34849,7]
Declarations in unreachable code! [main.b9fc88ca36935dab7714.bundle.js:34851,1]
Dropping unused variable scriptElements [main.b9fc88ca36935dab7714.bundle.js:34851,5]
Dropping unused variable scriptHost [main.b9fc88ca36935dab7714.bundle.js:34852,5]
Dropping unused function _fetchSylesFromState [main.b9fc88ca36935dab7714.bundle.js:35737,9]
Dropping unreachable code [main.b9fc88ca36935dab7714.bundle.js:37186,8]
Declarations in unreachable code! [main.b9fc88ca36935dab7714.bundle.js:37186,8]
Dropping unreachable code [main.b9fc88ca36935dab7714.bundle.js:37186,8]
Declarations in unreachable code! [main.b9fc88ca36935dab7714.bundle.js:37186,8]
Dropping unused variable renderMethod [main.b9fc88ca36935dab7714.bundle.js:40470,12]
Dropping unused variable __unused [main.b9fc88ca36935dab7714.bundle.js:41193,4]
Dropping unused variable __unused [main.b9fc88ca36935dab7714.bundle.js:43260,4]
Condition always true [main.b9fc88ca36935dab7714.bundle.js:47793,2]
Dropping unreachable code [main.b9fc88ca36935dab7714.bundle.js:47798,8]
Side effects in initialization of unused variable freeExports [main.b9fc88ca36935dab7714.bundle.js:47287,5]
Side effects in initialization of unused variable freeModule [main.b9fc88ca36935dab7714.bundle.js:47289,5]
Dropping unused variable key [main.b9fc88ca36935dab7714.bundle.js:47338,1]

WARNING in polyfills.7f6ab7464cbf8b193c44.bundle.js from UglifyJs
Condition left of || always false [polyfills.7f6ab7464cbf8b193c44.bundle.js:3431,63]
Condition left of || always false [polyfills.7f6ab7464cbf8b193c44.bundle.js:3432,62]
Dropping side-effect-free statement [polyfills.7f6ab7464cbf8b193c44.bundle.js:3460,21]
Side effects in initialization of unused variable Zone [polyfills.7f6ab7464cbf8b193c44.bundle.js:2983,5]
```

Getting below error in browser console:

`main.b9fc88c….bundle.js:2 Uncaught ReferenceError: process is not defined`

**Comment by filipesilva** [comment]
Those warnings are normal I think, right @TheLarkInn?

I just tried the following
```
ng new webpack-project --link-cli
cd webpack-project
ng serve -prod
```
and it seems to work. Did you change anything in your project?

**Comment by tapas4java** [comment]
Nope...I didn't change anything. 
I have followed below commands again and able to see the same issue.

```
ng new webpack-project --style scss --prefix db --link-cli
cd webpack-project
ng serve -prod
```

**Comment by filipesilva** [comment]
Did you maybe try playing around with mobile projects as well? The service worker might be caching files for you.

**Comment by TheLarkInn** [comment]
Yup the warning are UglifyJsPlugin informing you about the tree shaking and optimizations it's making. (We can suppress this if you feel it was confusing) 

In regards to the second question, to certify it's not the service worker cache tr ry loading the project in q new incognito window.

**Comment by filipesilva** [comment]
Actually it was the other way around - I had service worker cache that masked the error. I can reproduce it now as well on non-mobile projects.

**Comment by tapas4java** [comment]
@TheLarkInn I have tried loading the app in new incognito window but no luck.

**Comment by TheLarkInn** [comment]
Awesome. thank you for testing this. I know where the problem lies, I'm guessing `ng serve --dev` does run without problems?

**Comment by tapas4java** [comment]
@TheLarkInn You are welcome!

Yes... `ng serve` works fine 👍

**Comment by filipesilva** [comment]
@tapas4java should be fixed in https://github.com/angular/angular-cli/pull/1395

**Comment by tapas4java** [comment]
Awesome, everything works perfectly now except Live reload functionality in dev mode. When I do some changes, I can see the `[WDS] App hot update...` message on console but the UI is not getting updated actually.

**Comment by filipesilva** [comment]
@tapas4java https://github.com/angular/angular-cli/pull/1402 should fix that, thanks for finding it!

**Comment by tapas4java** [comment]
Great! When we are planning to merge this branch to master??

**Comment by filipesilva** [comment]
@tapas4java when it's ready (dissapointing, I know :p). 

It's a big PR with a lot of moving parts so we have to thoroughly test and review it.

**Comment by tapas4java** [comment]
I can understand @filipesilva

This weekend I am gonna start a medium size application on this cli . Will provide my feedback and help this branch to mature soon :)

**Comment by orangesoup** [comment]
@filipesilva I've been trying out the webpack branch for the last couple hours, but I've run into a problem (not sure if it's a bug): I'm using it with an existing project, but the `.scss` files in `app/public/styles/whatever.scss` seems like won't get compiled (they're just simply copied as I can see). What I've basically done is the following:

```
cd to/wherever/my/project/is
ng init (overwrite the files)
// fix couple things in the code to get webpack work
ng serve
```

The components use `.scss` too, and those seem to be working, it's just the files in the public dir which don't. Am I missing something?

**Comment by filipesilva** [comment]
@orangesoup actually, sass files in public aren't meant to be compiled on this branch. I kinda get your use-case here though... I guess you wanted some global stylesheet. 

Not sure we're gonna support compiling sass in public though. Tell me, would your be able to make it work with just sass support on components?

**Comment by orangesoup** [comment]
@filipesilva I'm using it for global stylesheets indeed. Can do a workaround probably, but I really liked this functionality in the old branch.

**Comment by filipesilva** [comment]
@TheLarkInn what do you about sass/less/stylus compilation of files in the public dir? Is it possible/reasonable?

**Comment by TheLarkInn** [comment]
We can definitely do it. Warrants discussion. Right now we are taking a per-component approach to implementing CSS.

**Comment by christianacca** [comment]
One option would be to keep a per-component approach and then use ExtractTextPlugin to bundle selected component stylesheets into one or more global css files.

I've been experimenting with this approach as I want to ensure the css just for the *application shell* to be rendered without having to wait for css embedded in JS.

It would seem logical to import the (scss) stylesheets as dependencies of the root component by convention.

**Comment by TheLarkInn** [comment]
@christianacca Absolutely makes sense. If we are using app-shell does that always prevent FOUC @jeffbcross ?

**Comment by orangesoup** [comment]
@filipesilva, @TheLarkInn One more weird thing is that vscode doesn't seem to like `Math` anymore. After the upgrade `Math.random(...)` (or any other `Math` function) says `Cannot find name 'Math'`. Previously it worked fine. Also, the build still happens and the code works just fine, it's just the editor complaining about it.

**Comment by filipesilva** [comment]
I've seen something similar with `Boolean` errors on manual tsc compilation actual, which seemed weird. Maybe it's related.

**Comment by orangesoup** [comment]
Yup, manually compiling with tsc gives me the following errors:

```
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
```

**Comment by orangesoup** [comment]
@TheLarkInn Your recent commit fixed the error with `Math`, however, now the same happening with `Map`.

**Comment by cortopy** [comment]
@orangesoup what about having a different folder, like "styles" and then importing what's needed in the component's scss file?

**Comment by TheLarkInn** [comment]
I actually like that idea @cortopy I also get FOUC is a concern. I wonder if app shell solvee this.

**Comment by cortopy** [comment]
@TheLarkInn  It's what I've been doing so far to use Foundation and Bootstrap. The drawback is that SASS variables (in the corresponding settings file) have to be imported on every sass file that require them. On a more positive note, I quite like the idea of just importing what I need, my sass workflow is very similar to writing a component ts file now.

**Comment by filipesilva** [comment]
@orangesoup make sure you're using a new project, as the last PR changed files on the generated project.

**Comment by orangesoup** [comment]
@cortopy I'll be honest: I'm really lazy (well.. probably most of us are). Let's say you have something that you would want to have in most of your components. It would really annoy me to import it into every single one of them (but it might be just me). I'm fine either way though,

One example: let's say you have some kind of layout scss (flex and stuff) which you would need probably in every component. Would you really want to import it in every single one of them?

**Comment by orangesoup** [comment]
@filipesilva I know, I'm always checking the commits and changing the code accordingly. Unless I've missed something `Map` is not there for some reason.

**Comment by cortopy** [comment]
@orangesoup answer is obviously no!! I've had to do the import thing so far as  I couldn't see other way. I don't have to import layouts though, only the vars/settings file. And since it is just one line, I use a snippet to reduce hassle. Layouts and any other framework styles go in the main app styles file. 

I totally agree though. It's not ideal, but at least it works

**Comment by filipesilva** [comment]
@orangesoup can you tell me the repro steps for me to see that error?

**Comment by orangesoup** [comment]
@filipesilva Just a simple `ng new name` and then add `let m: Map<string, int> = new Map<string, int>();` to your `app.component.ts` constructor or anywhere else.

**Comment by filipesilva** [comment]
Ok I tried those steps, but used `number` instead of `int`. `ng build` builds fine - BUT my editor (VSCode) complains about map.

I'm not sure if you're also using VSCode, but that's a problem on it's end because it doesn't support TS2.0  tsconfig options: https://github.com/Microsoft/vscode/issues/9232

**Comment by orangesoup** [comment]
Oh, sorry, it is number, not int, bit tired. I'm using VSCode, yes. Thanks for the link, I guess we'll just have to wait then!

**Comment by efriandika** [comment]
Please add to the 'Remaining action items' => `ng build -prod` will add cache busting strategy (add version or hash to the asset file)

💃

**Comment by filipesilva** [comment]
@efriandika it does that already :D

**Comment by efriandika** [comment]
It means it is available in the next release of angular-cli ? :D

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli/issues/1356#issuecomment-234154387, which is the best I can say :)

**Comment by efriandika** [comment]
Hehehe.. 💃 
Thanks for the information @filipesilva

**Comment by ivoviz** [comment]
@filipesilva `--host` flag doesn't seem to work. `ng serve --host "random.com"` still serves the content on `localhost`.  (`NG Live Development Server is running on http://localhost:4200.`). The help also says it should listen on all interfaces by default (that's how the old branch works at least), but this one definitely doesn't: running `ng serve` listens only on `127.0.0.1`, not `0.0.0.0`. The `--port` flag seems to work though.

**Comment by filipesilva** [comment]
@TheLarkInn can you have a look at @ivoviz's comment?

**Comment by frederikschubert** [comment]
I just tried out this branch together with the (RC 4) Offline Compilation and it all worked seamlessly! Can't wait for this to be released!

The only thing I found distracting were the warnings issued by several webpack plugins:
```
WARNING in CachePlugin - Cache cannot be used because of: DedupePlugin

WARNING in main.40c541f973fa25984d7c.bundle.js from UglifyJs
Condition left of && always true [main.40c541f973fa25984d7c.bundle.js:1144,17]
Side effects in initialization of unused variable ViewType [main.40c541f973fa25984d7c.bundle.js:3830,4]
Side effects in initialization of unused variable freeExports [main.40c541f973fa25984d7c.bundle.js:4764,4]
Side effects in initialization of unused variable freeModule [main.40c541f973fa25984d7c.bundle.js:4765,4]
Side effects in initialization of unused variable HTMLCollection [main.40c541f973fa25984d7c.bundle.js:9046,4]
Dropping unused variable SAFE_SRCSET_PATTERN [main.40c541f973fa25984d7c.bundle.js:13191,4]
Side effects in initialization of unused variable matchs [main.40c541f973fa25984d7c.bundle.js:15014,12]
Dropping unused variable __unused [main.40c541f973fa25984d7c.bundle.js:15314,4]
Dropping unused variable __unused [main.40c541f973fa25984d7c.bundle.js:17355,4]
Side effects in initialization of unused variable SecurityContext [main.40c541f973fa25984d7c.bundle.js:21544,4]
Condition always true [main.40c541f973fa25984d7c.bundle.js:23108,4]
Dropping unreachable code [main.40c541f973fa25984d7c.bundle.js:23111,7]
Declarations in unreachable code! [main.40c541f973fa25984d7c.bundle.js:23113,1]
Dropping unused variable scriptElements [main.40c541f973fa25984d7c.bundle.js:23113,5]
Dropping unused variable scriptHost [main.40c541f973fa25984d7c.bundle.js:23114,5]
Condition always true [main.40c541f973fa25984d7c.bundle.js:24660,2]
Dropping unreachable code [main.40c541f973fa25984d7c.bundle.js:24665,8]
Side effects in initialization of unused variable freeExports [main.40c541f973fa25984d7c.bundle.js:24154,5]
Side effects in initialization of unused variable freeModule [main.40c541f973fa25984d7c.bundle.js:24156,5]
Dropping unused variable key [main.40c541f973fa25984d7c.bundle.js:24205,1]
Dropping unused variable __unused [main.40c541f973fa25984d7c.bundle.js:29352,4]
Dropping unused variable __unused [main.40c541f973fa25984d7c.bundle.js:31023,4]

WARNING in polyfills.13671121984805e891bb.bundle.js from UglifyJs
Condition left of || always false [polyfills.13671121984805e891bb.bundle.js:3500,63]
Condition left of || always false [polyfills.13671121984805e891bb.bundle.js:3501,62]
Dropping side-effect-free statement [polyfills.13671121984805e891bb.bundle.js:3529,21]
Side effects in initialization of unused variable Zone [polyfills.13671121984805e891bb.bundle.js:3052,5]
```

This happens when using the `--prod` flag.

Is there anything one could do to prevent them? They are also visible in the console.

**Comment by TheLarkInn** [comment]
If you are running `ng serve` with --prod you will see the first warning. The second warning is to notify the user of optimizations and dead code elimination that is performed. Maybe we can look into adding a 'silenceWarnings' flag or something. I like the information but that's just personal taste and opinionz

**Comment by TheLarkInn** [comment]
@filipesilva I have a feature branch on my local that fixes this one specific feature. I just need to run tests and then setup a PR. If not today tomorrow for sure.

**Comment by TheLarkInn** [comment]
(That.is the host) we just need to set the host flag so 1. It defaults to 'localhost' and like above, set commandOptions.host to replace anywhere is serve.ts where `'localhost'` is referenced.

**Comment by frederikschubert** [comment]
@TheLarkInn Thinking more about it I don't think that a `silenceWarnings` flag would be needed as one rarely runs `ng serve --prod` for development purposes where these warnings could be distracting.
So forget my remark and continue the great work 👍

**Comment by mmrath** [comment]
@filipesilva @TheLarkInn Do you think webpack branch is ready to be used. I know this branch is not stable enough, which is OK. Apart from stability and minor new features, are there any major changes planned? 

Also how do I use global SASS files with this branch?

**Comment by filipesilva** [comment]
@mmrath this branch is not ready to be used. It is still under active development and we give no guarantees over what might or might not be changed. Until it goes into master it's not the official branch and there should be no expectation of support being given for it.

**Comment by mmrath** [comment]
@filipesilva Thanks for your reply.
Also I get the following warning when I used ngrx. Thought i just add it here, in case you already know it.

WARNING in ./~/@ngrx/core/SyncSubject.js
Cannot find source file '../../lib/SyncSubject.ts': Error: Can't resolve '../../lib/SyncSubject.ts' in '/Users/murali/Projects/dashboard-ui/node_modules/@ngrx/core'
 @ ./~/@ngrx/store/dispatcher.js 7:20-53
 @ ./~/@ngrx/store/index.js
 @ ./src/app/shared/api/http-interceptor.ts
 @ ./src/platform/browser-providers.ts
 @ ./src/platform/browser.ts
 @ ./src/main.ts
 @ multi main

**Comment by Brocco** [comment]
When I create a new project `ng new foo` I am not getting an initial commit on the repo instead all of the files are staged, but not actually committed.

**Comment by sunild** [comment]
Adding a question (from #1436) about fonts: Can the web pack config handle fonts from third party libs like Bootstrap in a generic way, or should there be a way for the user to specify a custom configuration for things like this? Or perhaps is this just something the developer needs to configure properly in their project?

Somewhat of a web pack newbie, apologies if this seems like a basic question :)

**Comment by filipesilva** [comment]
@mmrath I have not seen that error happen, no. Can you give me some reproduction steps so I can try to debug it?

**Comment by ivoviz** [comment]
@filipesilva It happens with angularfire2 as well, see: https://github.com/angular/angularfire2/issues/376.

**Comment by filipesilva** [comment]
So it's a typescript problem? Hm, odd. @TheLarkInn I guess we can update to TS2.0? 

I'd still like to know more about the issue and how to reproduce it... `angularfire2` doesn't even use TS2.0 itself, so I find it hard to believe it's a TS bug.

**Comment by ivoviz** [comment]
@filipesilva I'm pretty sure as well that TS2.0 has nothing to do with it. The main problem is the generated sourcemap files referencing to non-existent source files. Adding `src` from the angularfire2 repo manually, and changing the `sources` attribute in the `.map` files makes the warnings go away. Should probably just ask @davideast to fix the publishing so it goes away (and the ngrx guys as well).

**Comment by mmrath** [comment]
@filipesilva A sample repo located at https://github.com/mmrath/ng-cli-webpack-test . Please let me know if you are able to reproduce the issue with repo.

**Comment by hansl** [comment]
[Periscope](github.com/angular/periscope) also uses Angularfire2, and does not compile.

Output: https://gist.github.com/hansl/7b53915bfaa55d72ebe842807b0351e4

**Comment by filipesilva** [comment]
@Brocco I couldn't repro the `ng new` issue, this was my result:

```
kamik@T460p MINGW64 /D/sandbox
$ ng new git-project
(node:6048) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
installing ng2
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\environments\environment.dev.ts
  create src\app\environments\environment.prod.ts
  create src\app\environments\environment.ts
  create src\app\index.ts
  create src\app\shared\index.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\polyfills.ts
  create src\test.ts
  create src\tsconfig.json
  create src\typings.d.ts
  create angular-cli.json
  create config\environment.js
  create config\karma.conf.js
  create config\protractor.conf.js
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create e2e\typings.d.ts
  create .gitignore
  create package.json
  create public\.gitignore
  create public\.npmignore
  create tslint.json
  create typings.json
Successfully initialized git.
- Installing packages for tooling via npmtypings WARN deprecated 6/21/2016: "registry:dt/jasmine#2.2.0+20160412134438" is deprecated (updated, replaced or removed)
/ Installing packages for tooling via npm
├── angular-protractor (global dev)
├── jasmine (global dev)
└── selenium-webdriver (global dev)

Installed packages for tooling via npm.

kamik@T460p MINGW64 /D/sandbox
$ cd git-project/

kamik@T460p MINGW64 /D/sandbox/git-project (master)
$ git st
On branch master
nothing to commit, working directory clean

kamik@T460p MINGW64 /D/sandbox/git-project (master)
$ git log
commit ba79c687ffe8acf2c7e578665a2b4392f6caf871
Author: angular-cli <angular-cli@angular.io>
Date:   Mon Jul 25 20:49:49 2016 +0100

    chore: initial commit from angular-cli
```

We also test for git on our e2e test suite, which makes me think your scenario must have been a fluke (or something we're not testing for).
https://github.com/angular/angular-cli/blob/webpack/tests/e2e/e2e_workflow.spec.js#L82

**Comment by Meligy** [comment]
Hello everyone,
I'm not sure whether this is the best place to report this. I have been playing with the webpack branch (and [showing people how to do it][webpack], explaining it's not stable yet of course).
Someone asked me about using jQuery with that setup. I wouldn't recommend doing that in the first place, but my finding was interesting.

[webpack]: https://www.gurustop.net/blog/2016/07/24/angular2-angularcli-load-cli-from-git-github-master-webpack

Since we don't use separate typings for `e2e` and `src`, this means `src` gets the global `$` declaration from protractor. This throws TS error because of the conflicting declarations.

You can [see a sample error here][jquery]. I have also added to it some steps that can be used to separate the typings manually so that you don't get this error.
But, what I'm asking in this thread is: 

[jquery]: https://www.gurustop.net/blog/2016/07/24/3703/angular2-cli-jquery-webpack-protractor

Does it make sense to separate the typings for `src` and `e2e`?

(maybe via different tsconfig and types as mentioned in #1449?)

Thanks!

**Comment by jvbianchi** [comment]
Hi.
The output-path option on the build command is not working.
command: `ng build --output-path build/`

**Comment by TheLarkInn** [comment]
Just out of curiosity @jvbianchi can you try ./build as the output path and tell me if that works?

**Comment by jvbianchi** [comment]
@TheLarkInn I tried `./build` and it doesn't work, same problem.

**Comment by hansl** [comment]
Thanks everyone. This issue is now closed as the WebPack branch is merged. If you have build issues, please create separate issues on github instead of refering to this.

A NPM package will be published sometime this week with this. It will use a separate `dist-tag`, probably named `webpack`.

I want to specially thank @TheLarkInn and @filipesilva for their work on this. Without you, it's clear we'd still be using Broccoli.  Good work to both of you!

**Comment by yusijs** [comment]
Can't wait for this to hit npm! Hoping the upgrade path is ready to by then! :)

**Comment by itamark** [comment]
Was there a conclusion about the convention for global css?
I am also tending toward the concept of global scss folder at the root, that's imported as needed.
Let me know if it was resolved or still open - would love to develop the feature if it's not done yet.

**Comment by filipesilva** [comment]
@itamark see https://github.com/angular/angular-cli/pull/1633
