### ISSUE TITLE
Tracking: Documentation

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#2711]
Document the following areas of the CLI:
- [x] overview
- [x] new
- [x] init
- [x] generate
  - [x] component
  - [x] class
  - [x] directive
  - [x] enum
  - [x] interface
  - [x] module
  - [x] pipe
  - [x] service
- [x] test
- [x] build
- [x] e2e
- [x] get/set
- [x] docs
- [x] eject
- [x] lint
- [x] serve
- [x] `angular-cli.json`

Tasks:
- [x] Move readme documentation to the wiki (docs)

Stories for more details:
- [x] Setup AngularFire (PR - #3931)
- [x] Include bootstrap with CSS
- [x] Include Font Awesome (PR - #3898)
- [ ] Setup of global styles
- [x] Setup bootstrap with SASS (PR - #4067)
- [x] Setup Angular Material 2 (PR - #3897)
- [x] Setup Angular FlexLayout (PR - #4096)
- [ ] Configure package manager (Issue - #3886)
- [ ] Deployment steps (Firebase/Github)
- [ ] Setting up preprocessor paths (ref PR #4003)

Nice to have:
- [ ] Setup project with asp.net core #3578

Additional:
- [ ] Internationalization usage/story;
  - [ ] extraction
  - [ ] build
  - [ ] serve
  - [ ] deploy

**Comment by Puigcerber** [comment]
Hey guys! 

I thought about this yesterday when I discovered that all the `generate` commands have many options. Any idea of where to start? README.md or a separate guide?

Cheers.

**Comment by Brocco** [comment]
Still trying to figure that out for now, wanted to have a placeholder issue to track against.

**Comment by elvirdolic** [comment]
It would be great to put more docs to https://cli.angular.io/ with similiar doc style which is used on angular.io

**Comment by hansl** [comment]
Next action item:

- [ ] Move the WIKI content to `/docs/wiki` in the repo. The release should publish the wiki from git.

**Comment by Meet91** [comment]
Following this updated doc to integrate Bootstrap with angular-cli results into following module conflicts:

jquery.js
tether.js
Details errors are as below:

**ERROR in multi scripts
Module not found: Error: Can't resolve 'C:\word\angular-demo\node_modules\jquery\dist\jquery.js' in 'C:\word\angular-demo\node_modules\angular-cli\models'
@ multi scripts

ERROR in multi scripts
Module not found: Error: Can't resolve 'C:\word\angular-demo\node_modules\tether\dist\js\tether.js' in 'C:\word\angular-demo\node_modules\angular-cli\models'
@ multi scripts**

I'm using below configuration:
angular-cli: 1.0.0-beta.20-4
node: 7.1.0(npm-4.0.3)
os: win32 x64
bootstrap : 3.3.7

Any help in this matter would be really appreciated!

Thanks,
Mitesh

**Comment by Brocco** [comment]
@Meet91 I just verified my local app with no issues. Based upon your errors it seems like you're attempting to pull in more than just the bootstrap CSS as my guide suggests. If that's not the case please create a separate issue on this repo or post a question on StackOverflow. Make sure to either tag me in the issue and/or link to it here so I can find it. (I don't have a windows environment setup, so I'm testing on macOS v10.12.1)

**Comment by noelmace** [comment]
@Meet91 see https://github.com/angular/angular-cli/issues/3202#issuecomment-262928724
@Brocco do you think this issue stems from a bad understanding of some configuration, or should I create a merge request to update to README, waiting for some later resolution

**Comment by Meet91** [comment]
@noelmace I updated the angular-cli to beta.22-1 and error goes away and also tested with the bootstrap integration and all works great...Thank you so much for responding on such a short period!!!

**Comment by jeremymwells** [comment]
@Brocco - can you elaborate a little bit on what you had in mind for `Setup of global styles`?

**Comment by Brocco** [comment]
@jeremymwells global styles are the style files referenced via angular-cli.json this would be an overview of:

1) how to setup a reference here 
2) an overview of the implications of setting up a style here versus within an individual component

This is not meant to be a complicated explanation, just an overview on how to achieve application-wide styling.

**Comment by hansl** [comment]
Added i18n to your list, @Brocco.

**Comment by filipesilva** [comment]
@Brocco added `angular-cli.json` to the list.

**Comment by moniuch** [comment]
I would appreciate if angular-cli docs were constantly updated with minimum requirements of relevant dependencies, for each release.

**Comment by hansl** [comment]
I need to work on a serializer of the documentation for hte JSON Schema.

**Comment by hansl** [comment]
Considering this done. Expect more stories post 1.0.

@moniuch that's a great idea, but we're pretty lax on our requirements. The only relevant dependency is Angular and TypeScript :)

**Comment by itsnotvalid** [comment]
There is a mismatch to protrator.conf.json that the `project` line is not `e2e` but `e2e/tsconfig.e2e.json` from the generator output.
```javascript
beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
  },
```

**Comment by mtpultz** [comment]
Is there any reference to `Setup of global styles` that can be subscribed to on GitHub?

**Comment by mtpultz** [comment]
Found this in the docs https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/global-styles.md, but I think what I meant by that was is there a way to add global Sass variables for use with components.  Otherwise, you're always importing a variables file, palette file, etc throughout your Sass files.
