### ISSUE TITLE
Tracking: Lower Install Time.

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#3199]
- [x] Fork CompressionPlugin and remove Zopfli dependency.
- [ ] Make Sass Loader not directly depend on node-sass and install it only if/when needed.
- [ ] Remove direct dependency to protractor and show error message when `ng e2e` is run but protractor isn't in node modules.
- [ ] Remove direct dependency on karma and show an error message when `ng test` is run but karma isn't in node modules.
- [x] Drop bootstrapping time down to under 1 seconds on Travis (or in e2e in general).

**Comment by hansl** [comment]
Forking CompressionPlugin happened in #3414.

**Comment by hansl** [comment]
Cleaned up the package json and made a script to make sure we always depends on the exact dependencies, not more or less.

**Comment by Bulan** [comment]
I was about to create a new issue about not able to install since node-gyp requirement requires the server to access something other than npmjs.com (which our build server is locked down to only allow access to).

But found this #3428 the lead me here, so how far along is the "remove sass loader", any ETA since it seems to be next on the list?

**Comment by hansl** [comment]
Closing this as done;

1. we will not remove dependencies on protractor and karma before 1.0
2. the sass-loader plugin is useful for most people and the main users having problems (Chinese developers behind the firewall) can now use `cnpm` to install.

The install time went down significantly, and we have support for `yarn` as well which reduces further time.
