### ISSUE TITLE
TRACKING: third party licensing

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#3884]
Some of our direct and indirect dependencies are not using licenses that are approved by Google, so we need to do something about it. We have three options for each of those: ask authors to relicense, reimplement ourselves, or stop using the dependency.

Here's a (maybe incomplete) list:

- [x] `uc.micro` - WTFPL (from `markdown-it`). markdown-it might have replacements that are available, so I'll look for those.
- [x] `sourcemap-istanbul-instrumenter-loader` - WTFPL. We should probably contact the author for this one. Might not be needed.
- [x] `jsonify` - Public Domain (not a valid license, from `ember-cli-preprocess-registry/broccoli-clean-css/json-stable-stringify`). We don't need the preprocess-registry and will probably get rid of it.

Other point to consider this completed:

- [x] make a test to check licenses from package.json of every dependencies on Travis.

We might need to make separate issues to track some of those individually.

cc @IgorMinar @naomiblack

**Comment by hansl** [comment]
Shoutout to Robert Spier who found those!

**Comment by JohannesRudolph** [comment]
Alternative reading: Google's legal team should work on approving the WTFPL :-)

**Comment by filipesilva** [comment]
`sourcemap-istanbul-instrumenter-loader` is the only one missing now.

**Comment by filipesilva** [comment]
The `sourcemap-istanbul-instrumenter-loader` author at https://github.com/deepsweet/istanbul-instrumenter-loader/issues/39 seems to be ok with changing to MIT.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4561
