### ISSUE TITLE
Tracking: Styleguide Compliance

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#4137]
Modifications to angular-cli.json (including schema and TS definition file)

- [x] Reorganize by generation/blueprint (currently by configuration option)

Ensure support of the following options:

- [x] spec generation
- [x] flat folder
- [x] inline template (component only)
- [x] inline style (component only)
- [x] view encapsulation (component only)
- [x] change detection (component only)

**Comment by hansl** [comment]
See Filipe's document about defaults: https://docs.google.com/document/d/1_sY01kQTVE-WoNjHgd_hLmbUF5q9X4o10XbEJRyu06w/edit

**Comment by filipesilva** [comment]
Also: style guide says we separate 3rd party imports from app imports with a blank line. We should do a pass on the generated code for this.
