### ISSUE TITLE
RC.0 Release

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#4990]
- [x] Remove "production" wording from the microsite.
- [x] Consider upgrading `ExtractTextPlugin` to non-beta.
- [x] Create a `yarn.lock` file for projects and add it to the blueprints
  - [x] Based on package manager, install or not `yarn.lock`
  - [x] Automate the `yarn.lock` creation and validation
- [x] Merge the RC update guide
- [x] Publish the wiki
  - [x] Make sure every link is valid
- [x] Manually testing
  - [x] Windows
    - [x] Globally install Beta
    - [x] Uninstall Beta and `npm cache clean`
    - [x] Globally install RC.0
    - [x] `ng new --ng4 project-name`
    - [x] `ng build`
    - [x] `ng test`
    - [x] `ng e2e`
    - [x] `ng lint`
    - [x] `ng g component c-name`
    - [x] `ng test`
    - [x] `ng build --prod`
    - [x] `ng help`, `ng g --help`, `ng help e2e`
  - [x] Linux
    - [x] Globally install Beta
    - [x] Uninstall Beta and `npm cache clean`
    - [x] Globally install RC.0
    - [x] `ng new --ng4 project-name`
    - [x] `ng build`
    - [x] `ng test`
    - [x] `ng e2e`
    - [x] `ng lint`
    - [x] `ng g component c-name`
    - [x] `ng test`
    - [x] `ng build --prod`
    - [x] `ng help`, `ng g --help`, `ng help e2e`
  - [x] Mac OSX
    - [x] Globally install Beta
    - [x] Uninstall Beta and `npm cache clean`
    - [x] Globally install RC.0
    - [x] `ng new --ng4 project-name`
    - [x] `ng build`
    - [x] `ng test`
    - [x] `ng e2e`
    - [x] `ng lint`
    - [x] `ng g component c-name`
    - [x] `ng test`
    - [x] `ng build --prod`
    - [x] `ng help`, `ng g --help`, `ng help e2e`
  - [ ] Yarn on Linux
    - [ ] Globally install Beta
    - [ ] Globally install RC.0
    - [ ] `ng new --ng4 project-name`
    - [ ] `ng build`
    - [ ] `ng test`
    - [ ] `ng e2e`
    - [ ] `ng lint`
    - [ ] `ng g component c-name`
    - [ ] `ng test`
    - [ ] `ng build --prod`
    - [ ] `ng help`, `ng g --help`, `ng help e2e`
  - [x] Linux / Mac
    - [x] Ames
    - [ ] Angular IO
    - [x] Ejected Ames

- [ ] Automate release testing in Travis

**Comment by SanderElias** [comment]
Love the yarn additions. adding a yarn.lock will make deployments safer! 
(and not to mention, getting up and going a lot faster!)

**Comment by deebloo** [comment]
are there specific tasks for the microsite the team wants help with?

**Comment by SanderElias** [comment]
If you need help with manual testing Yarn on Linux, I'm happy to help!

**Comment by filipesilva** [comment]
@hansl is more action required here?
